

variables:
  GIT_SSL_NO_VERIFY: "1"

before_script:
- apt-get update
- apt-get install bzip2 -y
- apt-get install libmagickwand-6.q16-2 -y

.test_template: &test_definition
  # Uncomment below if you would like to run the tests on specific references
  # only, such as the branches `master`, `development`, etc.
  # only:
  #   - master
  #   - development
  script:
    # Let's run the tests. Substitute `coverage = false` below, if you do not
    # want coverage results.
    - julia -e 'Pkg.clone(pwd()); Pkg.test("DeformableRegistration",
      coverage = true)'
    # Comment out below if you do not want coverage results.
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("DeformableRegistration"));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

#test:0.6.0-dev:
#  image: julialang/julia:v0.6.0-dev
#  <<: *test_definition

test:0.6.2-dev:
  image: julia:0.6.2
  <<: *test_definition


# REMARK: Do not forget to enable the coverage feature for your project, if you
# are using code coverage reporting above. This can be done by
#
# - Navigating to the `CI/CD Pipelines` settings of your project,
# - Copying and pasting the default `Simplecov` regex example provided, i.e.,
#   `\(\d+.\d+\%\) covered` in the `test coverage parsing` textfield.
#
# WARNING: This template is using the `julialang/julia` images from [Docker
# Hub][3]. One can use custom Julia images and/or the official ones found
# in the same place. However, care must be taken to correctly locate the binary
# file (`/opt/julia/bin/julia` above), which is usually given on the image's
# description page.
#
# [3]: http://hub.docker.com/

