# see: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
install:
  - pip install matplotlib
script:
  - julia -e 'Pkg.clone("https://github.com/lruthotto/KrylovMethods.jl.git")'
matrix:
  allow_failures:
    - julia: nightly
